<!DOCTYPE html>
<html lang="en">
  <head>
  <?php echo $this->headMeta(); ?>
  <?php echo $this->headLink(); ?>
  <?php echo $this->headStyle(); ?>
  <?php echo $this->headScript(); ?>
  <?php echo $this->headTitle(); ?>
  <meta charset="utf-8">
      <title>Bootstrap, from Twitter</title>
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <meta name="description" content="">
      <meta name="author" content="">

      <!-- Le styles
      <link href="<?php echo $this->baseUrl(); ?>/bootstrap/css/bootstrap.css" rel="stylesheet">
      -->
      <link href="http://bootswatch.com/spacelab/bootstrap.min.css" rel="stylesheet">
      <style type="text/css">
          body {
              padding-top: 60px;
              padding-bottom: 40px;
          }
      </style>
      <link href="<?php echo $this->baseUrl(); ?>/bootstrap/css/bootstrap-responsive.css" rel="stylesheet">

      <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
      <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
      <![endif]-->

      <!-- Le fav and touch icons -->
      <link rel="shortcut icon" href="<?php echo $this->baseUrl(); ?>/bootstrap/ico/favicon.ico">
      <link rel="apple-touch-icon-precomposed" sizes="144x144" href="<?php echo $this->baseUrl(); ?>/bootstrap/ico/apple-touch-icon-144-precomposed.png">
      <link rel="apple-touch-icon-precomposed" sizes="114x114" href="<?php echo $this->baseUrl(); ?>/bootstrap/ico/apple-touch-icon-114-precomposed.png">
      <link rel="apple-touch-icon-precomposed" sizes="72x72" href="<?php echo $this->baseUrl(); ?>/bootstrap/ico/apple-touch-icon-72-precomposed.png">
      <link rel="apple-touch-icon-precomposed" href="<?php echo $this->baseUrl(); ?>/bootstrap/ico/apple-touch-icon-57-precomposed.png">

      <!-- BEGIN HOBO HEAD CODE -->
      <!-- hobo content helper -->
      <link rel="stylesheet" href="hobo/core/hobo.css">
      <!-- END HOBO HEAD CODE -->
  </head>
  <body>
  <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
          <div class="container">
              <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
              </a>
              <a class="brand" href="#">Hobo</a>
              <div class="nav-collapse">
                  <ul class="nav">
                      <li class="active"><a href="#">Overview</a></li>
                      <li><a href="#try">Try it out</a></li>
                      <li><a href="#contact">Contact</a></li>
                  </ul>
              </div><!--/.nav-collapse -->
          </div>
      </div>
  </div>


  <div class="container">
    <?php echo $this->layout()->content; ?>
      <footer data-hobo='{"isGlobal": true, "handle": "footer", "contentType": "plainText"}'>
          <p>&copy; Hobo Project <?php echo date('Y'); ?></p>
      </footer>
  </div>
  <!-- JavaScript at the bottom for fast page loading -->

  <!-- Grab Google CDN's jQuery
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
  -->
  <script src="<?php echo $this->baseUrl(); ?>/assets/scripts/jquery-1.7.1.min.js"></script>

  <!-- BEGIN HOBO SCRIPT CODE -->
  <!-- hobo content helper -->
  <script>
    var baseUrl = '<?php echo $this->baseUrl(); ?>';
    var routeName = '<?php echo $this->routeName; ?>';
  </script>
  <script src="hobo/core/hobo-core.js"></script>
  <!-- END HOBO SCRIPT CODE -->

  <!-- end scripts -->
</body>
</html>